#pragma once

#include <cstdint>
#include <map>
#include <string>
#include <utility>
#include <vector>

namespace econlife {

// =============================================================================
// Trade Infrastructure Types — TDD §18
// =============================================================================

// --- §18.1 — National Trade Offer ---

struct GoodOffer {
    uint32_t good_id;
    float quantity_available;  // units per simulated month
    float offer_price;         // per unit; production cost + margin
};

struct NationalTradeOffer {
    uint32_t nation_id;
    uint32_t tick_generated;
    std::vector<GoodOffer> exports;  // what this nation will sell
    std::vector<GoodOffer> imports;  // what this nation wants to buy (bids)
    // Regenerated by LOD 1 monthly update
};

// --- §18.2 — Global Commodity Price Index ---

struct GlobalCommodityPriceIndex {
    uint32_t last_updated_tick;
    std::map<uint32_t, float> lod2_price_modifier;
    // good_id -> multiplier on base spot price
    // Values > 1.0: LOD 2 world is net consuming (scarcity signal)
    // Values < 1.0: LOD 2 world is net producing (surplus signal)
    // Updated annually during LOD 2 batch job
    // Applied to LOD 0 and LOD 1 equilibrium price calculations
};

// --- §18.3 — Tariff Schedule and Trade Agreements ---

struct TradeAgreement {
    uint32_t partner_nation_id;
    float tariff_reduction;  // 0.0 = no effect; 1.0 = full free trade
    uint32_t signed_tick;
    uint32_t expires_tick;  // 0 = permanent unless dissolved
    bool is_active;
};

struct TariffSchedule {
    uint32_t nation_id;
    std::map<uint32_t, float> good_tariff_rates;  // good_id -> ad valorem rate
    float default_tariff_rate;
    std::vector<TradeAgreement> trade_agreements;
    // Embedded in Nation struct (§12) as TariffSchedule tariff_schedule.
    // Also indexed in WorldState as std::vector<TariffSchedule> tariff_schedules (one per nation).
};

// --- §18.8 — Route Profile (precomputed at world load) ---

struct RouteProfile {
    float distance_km;
    float route_terrain_roughness;  // max roughness along path
    float min_infrastructure;       // Minimum infrastructure level along route; range [0.0, 1.0];
                                    // affects transit time
    uint8_t hop_count;              // province boundaries crossed
    bool requires_sea_leg;
    bool requires_rail;
    float concealment_bonus;  // additive bonus to route_concealment_modifier on any
                              // TransitShipment dispatched along this route.
                              // Computed at route table build time as:
                              //   sum(config.routes.karst_concealment_bonus
                              //       for each province in province_path where has_karst == true)
                              // 0.0 for routes with no karst provinces.
                              // Capped by transit.max_concealment_modifier at dispatch.
    std::vector<uint32_t> province_path;  // intermediate provinces
};

// Route table: 6x6x5 entries for V1 = 180 RouteProfiles. Trivial memory cost.
// Stored at world load. Rebuilt when a province's infrastructure changes.
// Lookup at dispatch: O(1).
// using ProvinceRouteTable =
//     std::map<std::pair<uint32_t, uint32_t>, std::array<RouteProfile, 5>>;

// --- §18.9 — TransportMode, ShipmentStatus, TransitShipment ---

enum class TransportMode : uint8_t {
    road = 0,
    rail = 1,
    sea = 2,
    river = 3,
    air = 4,
};

enum class ShipmentStatus : uint8_t {
    in_transit = 0,
    arrived = 1,      // processed this tick; goods deposited into destination market
    intercepted = 2,  // criminal shipment seized; evidence token generated
    lost = 3,         // weather event / accident; goods destroyed
};

struct TransitShipment {
    uint32_t id;
    uint32_t good_id;
    float quantity_dispatched;
    float quantity_remaining;  // degrades each tick for perishables
    float quality_at_departure;
    float quality_current;  // degrades each tick for perishables
    uint32_t origin_province_id;
    uint32_t destination_province_id;
    uint32_t owner_id;  // player_id or npc_business_id
    uint32_t dispatch_tick;
    uint32_t arrival_tick;  // precomputed at dispatch; immutable
    TransportMode mode;
    float cost_paid;                   // deducted at dispatch
    bool is_criminal;                  // informal route; interception checks active
    float interception_risk_per_tick;  // computed at dispatch; 0.0 for legitimate
    bool is_concealed;                 // true if criminal operator selected alternate
                                       // low-visibility route: longer transit time,
                                       // lower interception_risk_per_tick
    float route_concealment_modifier;  // 0.0 (direct route) to
                                       // config.transit.max_concealment_modifier computed at
                                       // dispatch from RouteProfile selection; stored here for use
                                       // in per-tick interception checks (§18.10)
    ShipmentStatus status;

    // TransitShipment entries live in the DeferredWorkQueue with type = transit_arrival
    // and due_tick = arrival_tick. Criminal shipments additionally have one
    // interception_check item per in-transit tick queued at dispatch time.
    // All transit processing partitions by destination_province_id.
};

// --- §18.15 — NPC Physical Movement ---

enum class NPCTravelStatus : uint8_t {
    resident = 0,    // In home_province_id. Available for local actions. Default state.
    in_transit = 1,  // Physically moving between provinces. Cannot act at origin or destination.
                     // Criminal NPCs in transit carry interception risk (§18.10).
    visiting = 2,    // In a non-home province temporarily (arrived, not yet returned).
                     // Can act in current_province_id. Returns to home_province_id when
                     // visit reason concludes (meeting complete, campaign over, etc.).
};

// --- §18 appendix — Lod1NationStats ---

struct Lod1NationStats {
    std::map<uint32_t, float> production_by_good;   // good_id -> estimated units/month
    std::map<uint32_t, float> consumption_by_good;  // good_id -> estimated units/month
    // Written by the LOD 1 monthly update; read by the LOD 2 annual batch.
    // Stored in WorldState.lod1_national_stats as std::map<uint32_t, Lod1NationStats>.
};

}  // namespace econlife
